export const TALLERES = [
  // ✏️ Categoría: Dibujo (Azul)
  {
    id: 1,
    categoria: 'Dibujo',
    titulo: 'Fundamentos de Dibujo',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/fundamentosDibujo/fundamentosDibujo1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/fundamentosDibujo/fundamentosDibujo1.avif',
    ],
    descripcionCorta: ['✏️ Técnicas básicas', '📏 Proporción y forma'],
    descripcionCompleta:
      'Curso fundamental de dibujo que abarca los principios básicos esenciales. Desarrollarás habilidades de observación, comprensión de formas y volúmenes, y dominio de diferentes herramientas de dibujo. Un taller esencial para cualquier persona interesada en las artes visuales y base para otras disciplinas artísticas.',
    temario: [
      'Elementos básicos del dibujo: línea, forma, valor',
      'Técnicas de observación y medición',
      'Composición y equilibrio visual',
      'Perspectiva básica y espacialidad',
      'Luces y sombras: volumen y profundidad',
      'Ejercicios progresivos: bodegón, paisaje, figura humana básica',
      'Integración de conocimientos en proyecto personal',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Principiante',
    materiales: [
      'Set de lápices de grafito (HB a 6B)',
      'Cuaderno de dibujo',
      'Materiales básicos: goma, difumino, sacapuntas',
      'Carpeta para trabajos (incluida)',
    ],
    cupoMaximo: 15,
  },
  {
    id: 2,
    categoria: 'Dibujo',
    titulo: 'Retrato',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/retrato/retrato1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/retrato/retrato1.avif',
    ],
    descripcionCorta: ['👤 Expresión facial', '✏️ Realismo y proporción'],
    descripcionCompleta:
      'Taller especializado en el arte del retrato, abordando las proporciones del rostro humano, la captura de semejanzas y la expresión de la personalidad. Aprenderás técnicas específicas para representar ojos, nariz, boca y otros rasgos faciales, así como métodos para capturar la esencia de la persona retratada más allá del parecido físico.',
    temario: [
      'Anatomía del rostro humano',
      'Proporciones y medidas clásicas',
      'Técnicas para dibujar ojos, nariz, boca y orejas',
      'Representación del cabello y texturas de la piel',
      'Expresión y carácter en el retrato',
      'Iluminación y su efecto en el rostro',
      'Desarrollo de estilos personales: del realismo a la interpretación',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Intermedio',
    materiales: [
      'Set completo de lápices de grafito y carboncillo',
      'Papeles específicos para retrato',
      'Materiales complementarios: conté, sanguina',
      'Cuaderno de bocetos para práctica diaria',
    ],
    cupoMaximo: 10,
  },
  {
    id: 3,
    categoria: 'Dibujo',
    titulo: 'Anatomía',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/anatomia/anatomia1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/anatomia/anatomia1.avif',
    ],
    descripcionCorta: ['👤 Estructura corporal', '✏️ Proporciones humanas'],
    descripcionCompleta:
      'Curso especializado en anatomía artística para ilustradores y artistas. Aprenderás la estructura del cuerpo humano, proporciones, sistemas musculares y óseos desde un enfoque artístico. Dominarás la representación de poses dinámicas y expresivas basadas en conocimientos anatómicos sólidos.',
    temario: [
      'Proporciones del cuerpo humano',
      'Sistema óseo: estructura y mecánica',
      'Sistema muscular: forma y función',
      'Anatomía de superficie y landmarks',
      'Diferencias anatómicas por edad y género',
      'Representación de movimiento y peso',
      'Estilización anatómica para diferentes estilos artísticos',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Intermedio',
    materiales: [
      'Cuaderno de dibujo tamaño grande',
      'Set de lápices de grafito variados',
      'Materiales de sombreado',
      'Modelos anatómicos de referencia (disponibles en el taller)',
    ],
    cupoMaximo: 12,
  },
  {
    id: 4,
    categoria: 'Dibujo',
    titulo: 'Diseño de Personajes',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/disenoPersonajes/disenoPersonajes1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/disenoPersonajes/disenoPersonajes1.avif',
    ],
    descripcionCorta: ['🎭 Anatomía creativa', '🎨 Desarrollo de estilo'],
    descripcionCompleta:
      'Taller especializado en la creación y desarrollo de personajes para diversas aplicaciones: ilustración, animación, cómic y videojuegos. Aprenderás a diseñar personajes consistentes, expresivos y con personalidad definida, desde la conceptualización hasta su finalización.',
    temario: [
      'Anatomía básica y su estilización',
      'Desarrollo de arquetipos y personalidades',
      'Diseño de poses dinámicas y expresivas',
      'Creación de hojas modelo (model sheets)',
      'Vestuario, accesorios y elementos distintivos',
      'Expresión facial y corporal',
      'Adaptación de personajes a diferentes estilos',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Intermedio a avanzado',
    materiales: [
      'Cuaderno de bocetos profesional',
      'Set completo de lápices y materiales de coloreado',
      'Referencias anatómicas (incluidas)',
      'Tableta digitalizadora (recomendada pero opcional)',
    ],
    cupoMaximo: 10,
  },
  {
    id: 5,
    categoria: 'Dibujo',
    titulo: 'Perspectiva',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/perspectiva/perspectiva1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/perspectiva/perspectiva1.avif',
    ],
    descripcionCorta: ['🏙️ Escalas y profundidad', '📏 Puntos de fuga'],
    descripcionCompleta:
      'Taller especializado en la representación tridimensional de espacios y objetos. Aprenderás los principios de la perspectiva lineal y atmosférica, desde los fundamentos matemáticos hasta su aplicación artística. Ideal para ilustradores, diseñadores y artistas interesados en la representación convincente de espacios.',
    temario: [
      'Fundamentos de la perspectiva: conceptos y terminología',
      'Perspectiva de 1, 2 y 3 puntos de fuga',
      'Perspectiva atmosférica y efectos de profundidad',
      'Escalas y proporciones en el espacio',
      'Técnicas para espacios interiores y arquitectura',
      'Paisajes urbanos y naturales en perspectiva',
      'Integración de figuras y objetos en el espacio',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Intermedio',
    materiales: [
      'Reglas, escuadras y compás',
      'Papeles de formato grande',
      'Lápices técnicos de diferentes durezas',
      'Rotuladores calibrados (opcional)',
    ],
    cupoMaximo: 12,
  },
  {
    id: 6,
    categoria: 'Dibujo',
    titulo: 'Diseño de Escenarios',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/disenoEscenarios/disenoEscenarios1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/disenoEscenarios/disenoEscenarios1.avif',
    ],
    descripcionCorta: ['🏙️ Ambientes y espacios', '🖌️ Composición espacial'],
    descripcionCompleta:
      'Curso enfocado en la creación y diseño de escenarios y ambientes para diferentes medios: ilustración, animación, cómic y conceptos visuales. Aprenderás a diseñar espacios coherentes, atmosféricos y narrativamente funcionales, desde la conceptualización hasta el acabado final.',
    temario: [
      'Principios de diseño de escenarios',
      'Perspectiva aplicada a entornos complejos',
      'Uso del color y la luz para crear atmósfera',
      'Diseño de props y elementos ambientales',
      'Narrativa visual a través del espacio',
      'Escenarios para diferentes géneros y medios',
      'Proyecto final: desarrollo de concepto completo',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Intermedio a avanzado',
    materiales: [
      'Cuaderno de dibujo de formato amplio',
      'Materiales variados de dibujo y color',
      'Referencias y material visual',
      'Herramientas de perspectiva',
    ],
    cupoMaximo: 12,
  },
  {
    id: 7,
    categoria: 'Dibujo',
    titulo: 'Ilustración',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/ilustracion/ilustracion1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/ilustracion/ilustracion1.avif',
    ],
    descripcionCorta: ['🎨 Técnicas mixtas', '📚 Narrativa visual'],
    descripcionCompleta:
      'Taller integral de ilustración que abarca aspectos teóricos y prácticos de esta disciplina. Explorarás diversas técnicas, estilos y aplicaciones de la ilustración contemporánea, desarrollando proyectos prácticos orientados a diferentes contextos profesionales como editorial, conceptual y publicitario.',
    temario: [
      'Fundamentos de la ilustración contemporánea',
      'Proceso creativo: del concepto a la imagen final',
      'Técnicas mixtas y experimentación',
      'Ilustración narrativa y conceptual',
      'Aplicaciones prácticas: editorial, publicitaria, infantil',
      'Desarrollo de estilo personal',
      'Proyecto final según intereses del alumno',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Intermedio',
    materiales: [
      'Set completo de materiales de dibujo y color',
      'Cuaderno de ilustración',
      'Materiales específicos según proyecto personal',
      'Referencias bibliográficas',
    ],
    cupoMaximo: 12,
  },
  {
    id: 8,
    categoria: 'Dibujo',
    titulo: 'Narrativa Gráfica',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/narrativaGrafica/narracionGrafica1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/narrativaGrafica/narracionGrafica1.avif',
    ],
    descripcionCorta: ['📖 Cómic y storyboard', '✏️ Composición visual'],
    descripcionCompleta:
      'Curso completo sobre narración visual en formatos secuenciales como cómic, novela gráfica y storyboard. Aprenderás a combinar texto e imagen para contar historias efectivas, dominando aspectos como el ritmo narrativo, la composición de página y la comunicación visual.',
    temario: [
      'Fundamentos de narración visual y secuencial',
      'Estructura y anatomía del cómic',
      'Planificación de página y viñetas',
      'Composición para narrativa: encuadres y ángulos',
      'Creación de personajes para cómic',
      'Storyboard para cine y animación',
      'Proyecto final: desarrollo de historia corta',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Intermedio',
    materiales: [
      'Cuaderno de dibujo A4',
      'Lápices, rotuladores y materiales de entintado',
      'Plantillas para viñetas (incluidas)',
      'Referencias bibliográficas',
    ],
    cupoMaximo: 12,
  },

  // 🎨 Categoría: Pintura (Rojo)
  {
    id: 9,
    categoria: 'Pintura',
    titulo: 'Carbones',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/carbones/carbones1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/carbones/carbones1.avif',
    ],
    descripcionCorta: ['✏️ Técnica en seco', '🖤 Luces y sombras'],
    descripcionCompleta:
      'Taller especializado en la técnica del carboncillo, uno de los medios más expresivos y versátiles para el dibujo. Aprenderás desde los fundamentos hasta técnicas avanzadas, explorando las posibilidades expresivas de este material para crear obras con profundidad, dramatismo y un amplio rango tonal.',
    temario: [
      'Tipos de carboncillos y sus características',
      'Técnicas básicas: trazos, sombreados, difuminados',
      'Creación de valores tonales y contrastes',
      'Técnicas de sustracción y adición',
      'Uso de soportes y fijadores',
      'Combinación con otras técnicas en seco',
      'Proyecto personal guiado',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Todos los niveles',
    materiales: [
      'Set de carboncillos de diferentes durezas',
      'Papeles especiales para carboncillo',
      'Herramientas de difuminado y borrado',
      'Fijador (incluido)',
    ],
    cupoMaximo: 15,
  },
  {
    id: 10,
    categoria: 'Pintura',
    titulo: 'Gises Pastel',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/gisesPastel/gisesPastel1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/gisesPastel/gisesPastel1.avif',
    ],
    descripcionCorta: ['🖍️ Uso de pasteles', '🌈 Mezcla y difuminado'],
    descripcionCompleta:
      'Taller enfocado en la técnica de pasteles secos y grasos. Explorarás las cualidades únicas de este medio a medio camino entre el dibujo y la pintura. Aprenderás métodos para crear obras con una luminosidad y textura difícil de conseguir con otras técnicas, ideal para retratos y paisajes con un acabado aterciopelado.',
    temario: [
      'Tipos de pasteles: secos, grasos, lápices pastel',
      'Superficies y papeles adecuados',
      'Técnicas de aplicación y superposición',
      'Métodos de difuminado y mezcla',
      'Fijación y conservación de obras',
      'Efectos texturales y expresivos',
      'Desarrollo de proyectos: retrato, paisaje, abstracto',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Principiante a intermedio',
    materiales: [
      'Set básico de pasteles secos (24 colores)',
      'Papeles específicos para pastel',
      'Difuminos y herramientas de mezcla',
      'Fijador (incluido)',
    ],
    cupoMaximo: 10,
  },
  {
    id: 11,
    categoria: 'Pintura',
    titulo: 'Lápices de Colores',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/lapicesColores/lapizColor1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/lapicesColores/lapizColor1.avif',
    ],
    descripcionCorta: ['🌈 Técnicas de color', '✏️ Mezclas y capas'],
    descripcionCompleta:
      'Curso completo de ilustración con lápices de colores profesionales. Aprenderás técnicas avanzadas para conseguir resultados sorprendentes con este versátil medio, dominando la mezcla de colores, la creación de texturas y efectos que van desde lo hiperrealista hasta estilos más expresivos.',
    temario: [
      'Tipos de lápices de colores y sus características',
      'Técnicas de aplicación: capas, presión, dirección',
      'Teoría del color aplicada a lápices',
      'Métodos de mezcla y superposición',
      'Creación de texturas y efectos especiales',
      'Uso de solventes y medios auxiliares',
      'Desarrollo de proyecto personal',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Todos los niveles',
    materiales: [
      'Set de lápices de colores profesionales',
      'Papeles específicos para color',
      'Herramientas complementarias',
      'Material de referencia',
    ],
    cupoMaximo: 15,
  },
  {
    id: 12,
    categoria: 'Pintura',
    titulo: 'Tinta China',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/tintaChina/tintaChina1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/tintaChina/tintaChina1.avif',
    ],
    descripcionCorta: ['🖋️ Técnicas de línea', '✒️ Aguadas y texturas'],
    descripcionCompleta:
      'Taller especializado en la tinta china, explorando tanto la línea como la mancha. Aprenderás técnicas tradicionales y contemporáneas de este medio versátil, desde el dibujo lineal con plumilla hasta las aguadas con pincel. Un medio que permite tanto la precisión como la expresividad, ideal para obras de gran impacto visual.',
    temario: [
      'Materiales y herramientas: tintas, plumillas, pinceles',
      'Técnicas de línea: modulación y caligrafía',
      'Aguadas y valores tonales',
      'Texturas y efectos especiales',
      'Combinación con otras técnicas',
      'Influencias orientales y occidentales',
      'Desarrollo de estilo personal',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Intermedio',
    materiales: [
      'Set de plumillas y portaplumas',
      'Tinta china de calidad',
      'Pinceles específicos para aguada',
      'Papeles adecuados para tinta',
    ],
    cupoMaximo: 12,
  },
  {
    id: 13,
    categoria: 'Pintura',
    titulo: 'Acuarela',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/acuarela/acuarela1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/acuarela/acuarela1.avif',
    ],
    descripcionCorta: ['💧 Técnicas de agua', '🖌️ Degradados y transparencias'],
    descripcionCompleta:
      'Curso dedicado al arte de la acuarela, desde sus técnicas básicas hasta métodos avanzados. Aprenderás a dominar el agua como elemento principal, creando transparencias, lavados y efectos únicos. Un taller práctico donde la experimentación y el control técnico se complementan para desarrollar obras expresivas.',
    temario: [
      'Propiedades del papel y preparación',
      'Técnicas húmedo sobre húmedo y húmedo sobre seco',
      'Creación de degradados y transparencias',
      'Control del agua y los pigmentos',
      'Técnicas de reserva y enmascarado',
      'Efectos especiales: sal, alcohol, texturizantes',
      'Composición para acuarela: paisaje, botánica, abstracto',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Todos los niveles',
    materiales: [
      'Set de acuarelas (pastillas o tubos)',
      'Papeles de diferentes gramajes',
      'Pinceles específicos para acuarela',
      'Materiales de reserva y efectos',
    ],
    cupoMaximo: 12,
  },
  {
    id: 15,
    categoria: 'Pintura',
    titulo: 'Gouache',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/gouache/gouache1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/gouache/gouache1.avif',
    ],
    descripcionCorta: ['🖌️ Opacidad y brillantez', '🎨 Técnica versátil'],
    descripcionCompleta:
      'Taller dedicado al gouache, una técnica pictórica que combina características de la acuarela y el acrílico. Aprenderás a trabajar con este medio versátil que permite tanto transparencias como acabados opacos y mates, ideal para ilustración profesional y trabajos que requieren colores vivos y planos uniformes.',
    temario: [
      'Características y particularidades del gouache',
      'Diferencias con acuarela y acrílico',
      'Técnicas de aplicación: planos de color y degradados',
      'Uso de blanco y mezclas opacas',
      'Reutilización y correcciones',
      'Aplicaciones: ilustración, diseño, bellas artes',
      'Desarrollo de proyecto personal',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Todos los niveles',
    materiales: [
      'Set básico de gouache',
      'Pinceles específicos para gouache',
      'Papeles adecuados de diferentes texturas',
      'Paleta y materiales complementarios',
    ],
    cupoMaximo: 15,
  },
  {
    id: 16,
    categoria: 'Pintura',
    titulo: 'Acrílico',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/acrilico/acrilicos1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/acrilico/acrilicos1.avif',
    ],
    descripcionCorta: ['🎨 Pintura acrílica', '🖌️ Técnicas avanzadas'],
    descripcionCompleta:
      'Curso intensivo sobre pintura acrílica y sus múltiples posibilidades. Explorarás las ventajas de esta versátil técnica, incluyendo su rápido secado y la posibilidad de crear tanto efectos de acuarela como de óleo. Aprenderás técnicas experimentales y tradicionales para expandir tu expresión artística.',
    temario: [
      'Ventajas y limitaciones de la pintura acrílica',
      'Técnicas de aplicación en diferentes superficies',
      'Métodos para controlar el secado y la textura',
      'Uso de mediums y aditivos',
      'Técnicas experimentales: collage, transferencias',
      'Pintura acrílica con efectos mixtos',
      'Proyecto personal guiado',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Intermedio',
    materiales: [
      'Set de acrílicos (10 colores)',
      'Pinceles sintéticos variados',
      'Soportes mixtos: lienzo, papel, madera',
      'Mediums texturizantes (incluidos)',
    ],
    cupoMaximo: 15,
  },
  {
    id: 17,
    categoria: 'Pintura',
    titulo: 'Óleo',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/oleo/oleo1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/oleo/oleo1.avif',
    ],
    descripcionCorta: ['🖼️ Pintura con óleo', '🎨 Mezcla de colores'],
    descripcionCompleta:
      'Taller especializado en la técnica al óleo, desde sus aspectos básicos hasta aplicaciones avanzadas. Aprenderás las propiedades únicas de esta pintura, cómo trabajar por capas, técnicas de mezcla, y aplicarás estos conocimientos a través de diversos proyectos prácticos que evolucionan en complejidad.',
    temario: [
      'Propiedades y características del óleo',
      'Preparación de superficies y bases',
      'Técnicas de mezcla de colores y armonías',
      'Métodos de aplicación: alla prima, veladuras, impasto',
      'Trabajo en capas y tiempos de secado',
      'Composición para pintura al óleo',
      'Proyecto final: paisaje o bodegón',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Todos los niveles',
    materiales: [
      'Set de óleos (12 colores básicos)',
      'Pinceles variados para óleo',
      'Lienzos preparados (3 por mes)',
      'Medium y diluyentes (incluidos)',
    ],
    cupoMaximo: 12,
  },
  {
    id: 18,
    categoria: 'Pintura',
    titulo: 'Aerografía',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/aerografia/aerografia1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/aerografia/aerografia1.avif',
    ],
    descripcionCorta: ['🎨 Técnicas de aerógrafo', '🖌️ Aplicación en diseño'],
    descripcionCompleta:
      'Taller especializado en la técnica del aerógrafo, una herramienta versátil que permite crear acabados profesionales con gran precisión y suavidad. Aprenderás a utilizar y mantener el equipo, así como diversas técnicas para la aplicación en diferentes superficies y proyectos, desde ilustración hasta personalización de objetos.',
    temario: [
      'Introducción al aerógrafo: tipos y funcionamiento',
      'Mantenimiento y resolución de problemas comunes',
      'Técnicas básicas: degradados, texturas, enmascarado',
      'Control de presión y distancia',
      'Aplicación en diferentes superficies',
      'Efectos especiales: metalizados, transparencias, volumen',
      'Proyectos prácticos: ilustración, personalización',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Principiante a intermedio',
    materiales: [
      'Kit de aerógrafo básico (en préstamo durante el curso)',
      'Compresor de uso compartido',
      'Pinturas específicas para aerografía',
      'Materiales de enmascarado y superficies de práctica',
    ],
    cupoMaximo: 10,
  },

  // 💻 Categoría: Digital
  {
    id: 19,
    categoria: 'Digital',
    titulo: 'Gráficos Vectoriales',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/graficosVectoriales/graficosVectoriales1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/graficosVectoriales/graficosVectoriales1.avif',
    ],
    descripcionCorta: ['✒️ Ilustración vectorial', '🎨 Diseño de precisión'],
    descripcionCompleta:
      'Curso especializado en la creación y edición de gráficos vectoriales utilizando software profesional. Aprenderás a diseñar elementos escalables sin pérdida de calidad, ideales para logotipos, iconografía, ilustraciones y diseños que requieren precisión y versatilidad. Dominarás las herramientas fundamentales del diseño vectorial aplicadas a proyectos prácticos.',
    temario: [
      'Fundamentos del diseño vectorial',
      'Herramientas y funciones del software especializado',
      'Creación y edición de formas básicas y avanzadas',
      'Manejo de curvas Bézier y nodos',
      'Color, gradientes y efectos vectoriales',
      'Tipografía en entornos vectoriales',
      'Proyecto final: aplicación práctica según intereses',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Principiante a intermedio',
    materiales: [
      'Software de diseño vectorial',
      'Computadoras de la sala (con software instalado)',
      'Memoria USB para guardar proyectos',
      'Referencias y material de apoyo (incluido)',
    ],
    cupoMaximo: 10,
  },
  {
    id: 20,
    categoria: 'Digital',
    titulo: 'Imagen Corporativa',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/imgCoorporativa/imgCoorporativa1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/imgCoorporativa/imgCoorporativa1.avif',
    ],
    descripcionCorta: ['🏢 Branding', '🎨 Identidad visual'],
    descripcionCompleta:
      'Taller enfocado en el desarrollo de identidad visual y branding para empresas y proyectos. Aprenderás a crear sistemas visuales coherentes que comuniquen los valores y personalidad de una marca, desde el diseño de logotipos hasta la aplicación en diversos soportes y medios, abordando tanto aspectos conceptuales como técnicos.',
    temario: [
      'Fundamentos de branding e identidad corporativa',
      'Investigación y estrategia de marca',
      'Diseño de logotipos y sistemas visuales',
      'Paletas de color, tipografía y elementos gráficos',
      'Aplicaciones: papelería, digital, merchandising',
      'Desarrollo de manuales de identidad',
      'Proyecto final: creación de marca completa',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Intermedio',
    materiales: [
      'Software de diseño vectorial y edición',
      'Recursos digitales y plantillas',
      'Acceso a banco de imágenes y recursos',
      'Materiales para prototipado básico',
    ],
    cupoMaximo: 12,
  },
  {
    id: 21,
    categoria: 'Digital',
    titulo: 'Diseño Editorial / Pre-Prensa',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/disenoEditorialPrensa/disenoEditorialPrensa1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/disenoEditorialPrensa/disenoEditorialPrensa1.avif',
    ],
    descripcionCorta: ['📚 Maquetación', '🖨️ Preparación para impresión'],
    descripcionCompleta:
      'Curso especializado en diseño editorial y preparación de archivos para impresión profesional. Aprenderás a diseñar y maquetar publicaciones impresas de diversos formatos: libros, revistas, catálogos, folletos; dominando tanto los aspectos creativos como los técnicos necesarios para la correcta reproducción en imprenta.',
    temario: [
      'Fundamentos del diseño editorial',
      'Uso avanzado de software de maquetación',
      'Tipografía y jerarquía para publicaciones',
      'Retículas, composición y ritmo visual',
      'Gestión de imágenes y color para impresión',
      'Pre-prensa: preparación técnica de archivos',
      'Acabados especiales y encuadernación',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Intermedio',
    materiales: [
      'Software de maquetación y diseño',
      'Materiales de referencia y ejemplos',
      'Recursos digitales para prácticas',
      'Visita opcional a imprenta (según disponibilidad)',
    ],
    cupoMaximo: 10,
  },
  {
    id: 22,
    categoria: 'Digital',
    titulo: 'Foto Edición',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/fotoEdicion/fotoEdicion1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/fotoEdicion/fotoEdicion1.avif',
    ],
    descripcionCorta: ['📸 Retoque fotográfico', '🎨 Ajustes profesionales'],
    descripcionCompleta:
      'Taller especializado en edición y procesamiento digital de fotografías. Aprenderás técnicas profesionales para mejorar, corregir y transformar imágenes utilizando software especializado. Desde ajustes básicos hasta composiciones complejas y retoques avanzados, adquirirás las habilidades necesarias para obtener resultados de calidad profesional.',
    temario: [
      'Fundamentos de la edición fotográfica digital',
      'Interfaz y herramientas de software especializado',
      'Ajustes básicos: exposición, contraste, color',
      'Técnicas de selección y máscaras',
      'Retoque de piel y correcciones localizadas',
      'Trabajo con capas y modos de fusión',
      'Efectos creativos y estilización',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Principiante a intermedio',
    materiales: [
      'Software de edición fotográfica',
      'Banco de imágenes para prácticas',
      'Tableta digitalizadora (disponible en sala)',
      'Memoria USB para guardar proyectos',
    ],
    cupoMaximo: 10,
  },
  {
    id: 23,
    categoria: 'Digital',
    titulo: 'Ilustración Digital',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/ilustracionDigital/ilustracionDigital1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/ilustracionDigital/ilustracionDigital1.avif',
    ],
    descripcionCorta: ['🖥️ Pintura digital', '🎨 Técnicas avanzadas'],
    descripcionCompleta:
      'Curso completo de ilustración digital que abarca desde los fundamentos hasta técnicas avanzadas. Aprenderás a utilizar software profesional para crear ilustraciones de calidad, dominando herramientas, flujos de trabajo y métodos específicos del medio digital. Ideal para artistas tradicionales que desean explorar el mundo digital o principiantes interesados en esta disciplina.',
    temario: [
      'Introducción al software de ilustración digital',
      'Herramientas y funciones fundamentales',
      'Del boceto tradicional al acabado digital',
      'Uso de capas y modos de fusión',
      'Color digital: teoría y aplicación',
      'Pinceles y texturas personalizadas',
      'Workflow profesional y preparación de archivos',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Principiante a intermedio',
    materiales: [
      'Tableta gráfica (propia o préstamo con depósito)',
      'Software específico (licencia educativa incluida)',
      'Memoria USB para respaldo',
      'Acceso a computadoras del taller',
    ],
    cupoMaximo: 10,
  },
  {
    id: 24,
    categoria: 'Digital',
    titulo: 'Motion Graphics',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/motionGraphics/motionGraphics1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/motionGraphics/motionGraphics1.avif',
    ],
    descripcionCorta: ['🎬 Animación gráfica', '✨ Efectos visuales'],
    descripcionCompleta:
      'Taller especializado en motion graphics y animación de elementos gráficos para medios digitales y audiovisuales. Aprenderás a dar vida a logotipos, tipografías y elementos visuales utilizando software de composición y animación. Ideal para diseñadores que quieren expandir sus habilidades hacia el movimiento y lo audiovisual.',
    temario: [
      'Fundamentos de animación y motion graphics',
      'Interfaz y herramientas de software especializado',
      'Principios de animación aplicados al diseño',
      'Animación de texto y tipografía',
      'Efectos visuales y transiciones',
      'Integración de gráficos y video',
      'Proyecto final: pieza audiovisual completa',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Intermedio',
    materiales: [
      'Software de composición y animación',
      'Computadoras de alto rendimiento',
      'Banco de recursos y elementos para prácticas',
      'Disco duro externo recomendado',
    ],
    cupoMaximo: 8,
  },
  {
    id: 25,
    categoria: 'Digital',
    titulo: 'Edición de Video',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/edicionVideo/edicionVideo1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/edicionVideo/edicionVideo1.avif',
    ],
    descripcionCorta: ['🎬 Montaje audiovisual', '🎞️ Narrativa visual'],
    descripcionCompleta:
      'Curso completo de edición de video digital utilizando software profesional. Aprenderás desde los conceptos básicos hasta técnicas avanzadas para crear montajes audiovisuales efectivos y profesionales. Un taller práctico que cubre flujos de trabajo completos desde la importación de material hasta la exportación final para diferentes plataformas.',
    temario: [
      'Fundamentos de la edición audiovisual',
      'Uso profesional de software de edición',
      'Técnicas de montaje y narrativa visual',
      'Corrección de color básica',
      'Trabajo con audio: niveles y sincronización',
      'Efectos, transiciones y títulos',
      'Workflow profesional y formatos de exportación',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Principiante a intermedio',
    materiales: [
      'Software de edición no lineal',
      'Material audiovisual para prácticas',
      'Disco duro externo (requerido)',
      'Computadoras de alto rendimiento',
    ],
    cupoMaximo: 8,
  },
  {
    id: 26,
    categoria: 'Digital',
    titulo: 'Animación de Personajes 2D',
    imagen:
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/animacion2D/animacion2D1.avif',
    imagenes: [
      'https://epd.edu.mx/Pagina_Principal/Cursos/img/talleres/animacion2D/animacion2D1.avif',
    ],
    descripcionCorta: ['🎭 Personajes animados', '🎬 Movimiento expresivo'],
    descripcionCompleta:
      'Taller especializado en animación bidimensional de personajes. Aprenderás los principios fundamentales de la animación y su aplicación específica al movimiento de personajes, desde ciclos básicos de caminata hasta actuaciones más complejas y expresivas. Un curso práctico que combina fundamentos tradicionales con herramientas digitales.',
    temario: [
      'Principios fundamentales de la animación',
      'Estudio del movimiento y mecánica corporal',
      'Expresión facial y acting en personajes',
      'Creación de ciclos: caminar, correr, acciones repetitivas',
      'Peso, timing y anticipación',
      'Lip sync básico y animación de diálogo',
      'Proyecto final: escena animada con personaje',
    ],
    fechaInscripcion: 'Primera semana del mes',
    costoInscripcion: '$500 MXN',
    colegiatura: '$3000 MXN',
    duracion: '30 horas',
    horarios: [
      'Lunes a viernes 12:00-14:00',
      'Preguntar por disponibilidad en sabatino',
    ],
    nivel: 'Intermedio',
    materiales: [
      'Software de animación 2D',
      'Tableta gráfica (requerida)',
      'Biblioteca de personajes para prácticas',
      'Disco duro externo para proyectos',
    ],
    cupoMaximo: 8,
  },
];
