export const TALLERES = [
  // 🎨 Categoría: Pintura (Rojo)
  {
    id: 1,
    categoria: 'Pintura',
    titulo: 'Taller de Pintura',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1579965342575-16428a7c8881',
      'https://images.unsplash.com/photo-1559638753-d8fca66e5e8d',
    ],
    descripcionCorta: ['🎨 Técnicas mixtas', '🖌️ Aplicación de color'],
    descripcionCompleta:
      'Curso introductorio a diversas técnicas pictóricas. Los estudiantes explorarán desde los fundamentos del color hasta la aplicación práctica en diferentes medios. Ideal para principiantes que desean adquirir una base sólida en pintura o artistas intermedios que buscan ampliar sus habilidades.',
    temario: [
      'Fundamentos del color y teoría cromática',
      'Introducción a diferentes medios: óleo, acrílico, acuarela',
      'Técnicas de composición y equilibrio visual',
      'Aplicación de luz y sombra',
      'Creación de texturas y efectos',
      'Desarrollo de estilo personal',
    ],
    fechaInscripcion: '15 de abril',
    costoInscripcion: '$500 MXN',
    colegiatura: '$1200 MXN/mes',
    duracion: '3 meses',
    horarios: ['Lunes y miércoles 16:00-18:00', 'Sábados 10:00-14:00'],
    nivel: 'Principiante a intermedio',
    materiales: [
      'Kit básico de pinceles (incluido)',
      'Lienzos (2 por mes)',
      'Set de pinturas según técnica elegida',
    ],
    profesor: 'Mtra. Elena Ramírez',
    cupoMaximo: 15,
  },
  {
    id: 2,
    categoria: 'Pintura',
    titulo: 'Óleo',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1577085676811-4a44f31f8b6b',
      'https://images.unsplash.com/photo-1584847319479-6dc62ebe56cb',
    ],
    descripcionCorta: ['🖼️ Pintura con óleo', '🎨 Mezcla de colores'],
    descripcionCompleta:
      'Taller especializado en la técnica al óleo, desde sus aspectos básicos hasta aplicaciones avanzadas. Aprenderás las propiedades únicas de esta pintura, cómo trabajar por capas, técnicas de mezcla, y aplicarás estos conocimientos a través de diversos proyectos prácticos que evolucionan en complejidad.',
    temario: [
      'Propiedades y características del óleo',
      'Preparación de superficies y bases',
      'Técnicas de mezcla de colores y armonías',
      'Métodos de aplicación: alla prima, veladuras, impasto',
      'Trabajo en capas y tiempos de secado',
      'Composición para pintura al óleo',
      'Proyecto final: paisaje o bodegón',
    ],
    fechaInscripcion: '10 de abril',
    costoInscripcion: '$550 MXN',
    colegiatura: '$1300 MXN/mes',
    duracion: '4 meses',
    horarios: ['Martes y jueves 17:00-19:00', 'Sábados 15:00-19:00'],
    nivel: 'Todos los niveles',
    materiales: [
      'Set de óleos (12 colores básicos)',
      'Pinceles variados para óleo',
      'Lienzos preparados (3 por mes)',
      'Medium y diluyentes (incluidos)',
    ],
    profesor: 'Mtro. Roberto Méndez',
    cupoMaximo: 12,
  },
  {
    id: 3,
    categoria: 'Pintura',
    titulo: 'Acrílico',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1560421741-6551b3ff7a74',
      'https://images.unsplash.com/photo-1510832842230-87253f48d74f',
    ],
    descripcionCorta: ['🎨 Pintura acrílica', '🖌️ Técnicas avanzadas'],
    descripcionCompleta:
      'Curso intensivo sobre pintura acrílica y sus múltiples posibilidades. Explorarás las ventajas de esta versátil técnica, incluyendo su rápido secado y la posibilidad de crear tanto efectos de acuarela como de óleo. Aprenderás técnicas experimentales y tradicionales para expandir tu expresión artística.',
    temario: [
      'Ventajas y limitaciones de la pintura acrílica',
      'Técnicas de aplicación en diferentes superficies',
      'Métodos para controlar el secado y la textura',
      'Uso de mediums y aditivos',
      'Técnicas experimentales: collage, transferencias',
      'Pintura acrílica con efectos mixtos',
      'Proyecto personal guiado',
    ],
    fechaInscripcion: '20 de abril',
    costoInscripcion: '$500 MXN',
    colegiatura: '$1100 MXN/mes',
    duracion: '3 meses',
    horarios: ['Miércoles y viernes 16:00-18:00', 'Domingos 10:00-14:00'],
    nivel: 'Intermedio',
    materiales: [
      'Set de acrílicos (10 colores)',
      'Pinceles sintéticos variados',
      'Soportes mixtos: lienzo, papel, madera',
      'Mediums texturizantes (incluidos)',
    ],
    profesor: 'Mtra. Carolina López',
    cupoMaximo: 15,
  },
  {
    id: 4,
    categoria: 'Pintura',
    titulo: 'Acuarela',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1461344577544-4e5dc9487184',
      'https://images.unsplash.com/photo-1513364776144-60967b0f800f',
    ],
    descripcionCorta: ['💧 Técnicas de agua', '🖌️ Degradados y transparencias'],
    descripcionCompleta:
      'Curso dedicado al arte de la acuarela, desde sus técnicas básicas hasta métodos avanzados. Aprenderás a dominar el agua como elemento principal, creando transparencias, lavados y efectos únicos. Un taller práctico donde la experimentación y el control técnico se complementan para desarrollar obras expresivas.',
    temario: [
      'Propiedades del papel y preparación',
      'Técnicas húmedo sobre húmedo y húmedo sobre seco',
      'Creación de degradados y transparencias',
      'Control del agua y los pigmentos',
      'Técnicas de reserva y enmascarado',
      'Efectos especiales: sal, alcohol, texturizantes',
      'Composición para acuarela: paisaje, botánica, abstracto',
    ],
    fechaInscripcion: '25 de abril',
    costoInscripcion: '$450 MXN',
    colegiatura: '$1000 MXN/mes',
    duracion: '3 meses',
    horarios: ['Lunes y jueves 17:00-19:00', 'Sábados 9:00-13:00'],
    nivel: 'Todos los niveles',
    materiales: [
      'Set de acuarelas (pastillas o tubos)',
      'Papeles de diferentes gramajes',
      'Pinceles específicos para acuarela',
      'Materiales de reserva y efectos',
    ],
    profesor: 'Mtro. Daniel Torres',
    cupoMaximo: 12,
  },
  {
    id: 5,
    categoria: 'Pintura',
    titulo: 'Gises Pastel',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1517697471339-4aa32003c11a',
      'https://images.unsplash.com/photo-1596350351182-c2ce5b74a758',
    ],
    descripcionCorta: ['🖍️ Uso de pasteles', '🌈 Mezcla y difuminado'],
    descripcionCompleta:
      'Taller enfocado en la técnica de pasteles secos y grasos. Explorarás las cualidades únicas de este medio a medio camino entre el dibujo y la pintura. Aprenderás métodos para crear obras con una luminosidad y textura difícil de conseguir con otras técnicas, ideal para retratos y paisajes con un acabado aterciopelado.',
    temario: [
      'Tipos de pasteles: secos, grasos, lápices pastel',
      'Superficies y papeles adecuados',
      'Técnicas de aplicación y superposición',
      'Métodos de difuminado y mezcla',
      'Fijación y conservación de obras',
      'Efectos texturales y expresivos',
      'Desarrollo de proyectos: retrato, paisaje, abstracto',
    ],
    fechaInscripcion: '18 de abril',
    costoInscripcion: '$500 MXN',
    colegiatura: '$1200 MXN/mes',
    duracion: '3 meses',
    horarios: ['Martes y viernes 16:00-18:00', 'Domingos 10:00-14:00'],
    nivel: 'Principiante a intermedio',
    materiales: [
      'Set básico de pasteles secos (24 colores)',
      'Papeles específicos para pastel',
      'Difuminos y herramientas de mezcla',
      'Fijador (incluido)',
    ],
    profesor: 'Mtra. Gabriela Sánchez',
    cupoMaximo: 10,
  },

  // ✏️ Categoría: Dibujo (Verde)
  {
    id: 6,
    categoria: 'Dibujo',
    titulo: 'Taller de Dibujo',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1602738328654-51ab2ae6c4ff',
      'https://images.unsplash.com/photo-1581354883434-54b812d3dfbc',
    ],
    descripcionCorta: ['📏 Proporción y anatomía', '✏️ Técnicas básicas'],
    descripcionCompleta:
      'Curso fundamental de dibujo que abarca desde los principios básicos hasta técnicas intermedias. Desarrollarás habilidades de observación, comprensión de formas y volúmenes, y dominio de diferentes herramientas de dibujo. Un taller esencial para cualquier persona interesada en las artes visuales y base para otras disciplinas artísticas.',
    temario: [
      'Elementos básicos del dibujo: línea, forma, valor',
      'Técnicas de observación y medición',
      'Composición y equilibrio visual',
      'Perspectiva básica y espacialidad',
      'Luces y sombras: volumen y profundidad',
      'Ejercicios progresivos: bodegón, paisaje, figura humana básica',
      'Integración de conocimientos en proyecto personal',
    ],
    fechaInscripcion: '15 de abril',
    costoInscripcion: '$450 MXN',
    colegiatura: '$1200 MXN/mes',
    duracion: '4 meses',
    horarios: ['Lunes y miércoles 17:00-19:00', 'Sábados 10:00-14:00'],
    nivel: 'Principiante',
    materiales: [
      'Set de lápices de grafito (HB a 6B)',
      'Cuaderno de dibujo',
      'Materiales básicos: goma, difumino, sacapuntas',
      'Carpeta para trabajos (incluida)',
    ],
    profesor: 'Mtro. Alejandro Ruiz',
    cupoMaximo: 15,
  },
  {
    id: 7,
    categoria: 'Dibujo',
    titulo: 'Dibujo Básico',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1520333789090-1afc82db536a',
      'https://images.unsplash.com/photo-1595079160287-95481c23bd7d',
    ],
    descripcionCorta: ['📝 Fundamentos', '✏️ Sombras y texturas'],
    descripcionCompleta:
      'Introducción práctica al dibujo para personas sin experiencia previa. Este curso te llevará paso a paso desde los ejercicios más simples hasta la realización de dibujos con volumen y textura. Se enfoca en desarrollar la coordinación mano-ojo y la comprensión de las formas básicas que componen todos los objetos.',
    temario: [
      'Ejercicios de coordinación y trazo',
      'Formas geométricas básicas y su aplicación',
      'Introducción al sombreado y valores tonales',
      'Representación de texturas básicas',
      'Principios de composición',
      'De lo bidimensional a lo tridimensional',
      'Proyectos graduales: de objetos simples a composiciones',
    ],
    fechaInscripcion: '10 de abril',
    costoInscripcion: '$400 MXN',
    colegiatura: '$1000 MXN/mes',
    duracion: '3 meses',
    horarios: ['Martes y jueves 16:00-18:00', 'Sábados 15:00-19:00'],
    nivel: 'Principiante absoluto',
    materiales: [
      'Kit básico de dibujo (incluido)',
      'Cuaderno de dibujo de papel adecuado',
      'Portafolio para organizar trabajos',
    ],
    profesor: 'Mtra. Laura Gutiérrez',
    cupoMaximo: 12,
  },
  {
    id: 8,
    categoria: 'Dibujo',
    titulo: 'Retrato',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1626544827763-d516dce335e2',
      'https://images.unsplash.com/photo-1594837101218-1cc0a15176aa',
    ],
    descripcionCorta: ['👤 Expresión facial', '🖍️ Realismo y proporción'],
    descripcionCompleta:
      'Taller especializado en el arte del retrato, abordando las proporciones del rostro humano, la captura de semejanzas y la expresión de la personalidad. Aprenderás técnicas específicas para representar ojos, nariz, boca y otros rasgos faciales, así como métodos para capturar la esencia de la persona retratada más allá del parecido físico.',
    temario: [
      'Anatomía del rostro humano',
      'Proporciones y medidas clásicas',
      'Técnicas para dibujar ojos, nariz, boca y orejas',
      'Representación del cabello y texturas de la piel',
      'Expresión y carácter en el retrato',
      'Iluminación y su efecto en el rostro',
      'Desarrollo de estilos personales: del realismo a la interpretación',
    ],
    fechaInscripcion: '20 de abril',
    costoInscripcion: '$550 MXN',
    colegiatura: '$1300 MXN/mes',
    duracion: '4 meses',
    horarios: ['Miércoles y viernes 17:00-19:00', 'Domingos 10:00-14:00'],
    nivel: 'Intermedio',
    materiales: [
      'Set completo de lápices de grafito y carboncillo',
      'Papeles específicos para retrato',
      'Materiales complementarios: conté, sanguina',
      'Cuaderno de bocetos para práctica diaria',
    ],
    profesor: 'Mtro. Fernando Vázquez',
    cupoMaximo: 10,
  },
  {
    id: 9,
    categoria: 'Dibujo',
    titulo: 'Caricatura',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1608889825103-eb5ed706fc64',
      'https://images.unsplash.com/photo-1577460551100-907fc393c606',
    ],
    descripcionCorta: ['🤣 Exageración facial', '🖊️ Expresión y estilo'],
    descripcionCompleta:
      'Curso dinámico sobre el arte de la caricatura y la exageración controlada. Aprenderás a identificar los rasgos distintivos de un rostro y a enfatizarlos de manera humorística pero reconocible. Desarrollarás un estilo propio explorando diferentes técnicas y aproximaciones a este arte que combina observación, humor y síntesis gráfica.',
    temario: [
      'Fundamentos de la caricatura: exageración vs. reconocimiento',
      'Identificación de rasgos distintivos',
      'Técnicas de simplificación y estilización',
      'Expresión de emociones y personalidad',
      'Desarrollo de personajes y estilos propios',
      'Caricatura rápida y de evento',
      'Aplicaciones: ilustración, cómic, animación básica',
    ],
    fechaInscripcion: '18 de abril',
    costoInscripcion: '$500 MXN',
    colegiatura: '$1200 MXN/mes',
    duracion: '3 meses',
    horarios: ['Martes y jueves 17:00-19:00', 'Sábados 10:00-14:00'],
    nivel: 'Todos los niveles',
    materiales: [
      'Set de plumones profesionales',
      'Lápices de colores y rotuladores',
      'Cuaderno de bocetos',
      'Tableta digitalizadora (opcional)',
    ],
    profesor: 'Mtro. Ignacio Pérez',
    cupoMaximo: 15,
  },
  {
    id: 10,
    categoria: 'Dibujo',
    titulo: 'Perspectiva de Escenarios',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1594804233314-6b16fa858fef',
      'https://images.unsplash.com/photo-1519974719765-e6559eac2575',
    ],
    descripcionCorta: ['🏙️ Escalas y profundidad', '📏 Puntos de fuga'],
    descripcionCompleta:
      'Taller especializado en la representación tridimensional de espacios y escenarios. Aprenderás los principios de la perspectiva lineal y atmosférica, desde los fundamentos matemáticos hasta su aplicación artística. Ideal para ilustradores, diseñadores y artistas interesados en la representación convincente de espacios interiores y exteriores.',
    temario: [
      'Fundamentos de la perspectiva: conceptos y terminología',
      'Perspectiva de 1, 2 y 3 puntos de fuga',
      'Perspectiva atmosférica y efectos de profundidad',
      'Escalas y proporciones en el espacio',
      'Técnicas para espacios interiores y arquitectura',
      'Paisajes urbanos y naturales en perspectiva',
      'Integración de figuras y objetos en el espacio',
    ],
    fechaInscripcion: '12 de abril',
    costoInscripcion: '$500 MXN',
    colegiatura: '$1100 MXN/mes',
    duracion: '3 meses',
    horarios: ['Lunes y miércoles 16:00-18:00', 'Sábados 15:00-19:00'],
    nivel: 'Intermedio',
    materiales: [
      'Reglas, escuadras y compás',
      'Papeles de formato grande',
      'Lápices técnicos de diferentes durezas',
      'Rotuladores calibrados (opcional)',
    ],
    profesor: 'Mtro. Arturo Mendoza',
    cupoMaximo: 12,
  },
  {
    id: 11,
    categoria: 'Dibujo',
    titulo: 'Perspectiva de Objetos',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1560419184-b7d5525c97e5',
      'https://images.unsplash.com/photo-1593073862407-a3ce22748763',
    ],
    descripcionCorta: ['🔺 Volumen y forma', '📐 Ilusión tridimensional'],
    descripcionCompleta:
      'Curso enfocado en la representación tridimensional de objetos y cuerpos geométricos. Dominarás las técnicas para crear volumen y profundidad convincentes, aplicando principios de perspectiva y sombreado a objetos cotidianos y formas complejas. Especialmente útil para diseñadores industriales, ilustradores y artistas conceptuales.',
    temario: [
      'Geometría básica y construcción de volúmenes',
      'Perspectiva aplicada a objetos aislados',
      'Técnicas de sombreado para crear volumen',
      'Representación de texturas y materiales',
      'Objetos complejos: descomposición y reconstrucción',
      'Luz y sombra: valores tonales y reflejos',
      'Composiciones de múltiples objetos',
    ],
    fechaInscripcion: '14 de abril',
    costoInscripcion: '$500 MXN',
    colegiatura: '$1100 MXN/mes',
    duracion: '3 meses',
    horarios: ['Martes y jueves 17:00-19:00', 'Domingos 9:00-13:00'],
    nivel: 'Intermedio',
    materiales: [
      'Juego de lápices de grafito (H a 8B)',
      'Papeles de diferentes texturas',
      'Herramientas de medición y perspectiva',
      'Kit de sombreado (difuminos, borrador de precisión)',
    ],
    profesor: 'Mtra. Julia Morales',
    cupoMaximo: 15,
  },
  {
    id: 12,
    categoria: 'Dibujo',
    titulo: 'Entintado',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4',
      'https://images.unsplash.com/photo-1595079676339-1534801ad6cf',
    ],
    descripcionCorta: ['🖋️ Técnicas de línea', '✏️ Expresión y detalle'],
    descripcionCompleta:
      'Taller especializado en técnicas de dibujo a tinta, desde el uso de plumillas tradicionales hasta rotuladores modernos. Aprenderás a crear obras de gran impacto visual utilizando únicamente líneas y puntos, dominando el contraste, la textura y la expresividad que caracterizan al entintado profesional. Ideal para ilustradores e interesados en cómic y narrativa gráfica.',
    temario: [
      'Herramientas de entintado: plumillas, estilógrafos, pinceles',
      'Técnicas de línea: modulación y expresividad',
      'Texturas y tramas: punteado, rayado, tramado',
      'Del boceto al entintado: proceso y metodología',
      'Corrección y solución de errores',
      'Volumen y espacio a través de la línea',
      'Desarrollo de estilo personal',
    ],
    fechaInscripcion: '22 de abril',
    costoInscripcion: '$550 MXN',
    colegiatura: '$1200 MXN/mes',
    duracion: '3 meses',
    horarios: ['Lunes y viernes 17:00-19:00', 'Sábados 15:00-19:00'],
    nivel: 'Intermedio a avanzado',
    materiales: [
      'Set de plumillas y portaplumas',
      'Tintas de diferentes tipos',
      'Papeles especiales para entintado',
      'Rotuladores calibrados variados',
    ],
    profesor: 'Mtro. Manuel Herrera',
    cupoMaximo: 12,
  },
  {
    id: 13,
    categoria: 'Dibujo',
    titulo: 'Narrativa Gráfica',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1600096194534-95cf5ece04cf',
      'https://images.unsplash.com/photo-1618519764620-7403abdbdfe9',
    ],
    descripcionCorta: ['📖 Cómic y storyboard', '✏️ Composición visual'],
    descripcionCompleta:
      'Curso completo sobre narración visual en formatos secuenciales como cómic, novela gráfica y storyboard. Aprenderás a combinar texto e imagen para contar historias efectivas, dominando aspectos como el ritmo narrativo, la composición de página y la comunicación visual. Un taller práctico que culmina en la creación de un proyecto narrativo personal.',
    temario: [
      'Fundamentos de narración visual y secuencial',
      'Estructura y anatomía del cómic',
      'Planificación de página y viñetas',
      'Composición para narrativa: encuadres y ángulos',
      'Creación de personajes para cómic',
      'Storyboard para cine y animación',
      'Proyecto final: desarrollo de historia corta',
    ],
    fechaInscripcion: '25 de abril',
    costoInscripcion: '$550 MXN',
    colegiatura: '$1200 MXN/mes',
    duracion: '4 meses',
    horarios: ['Miércoles y viernes 16:00-18:00', 'Sábados 10:00-14:00'],
    nivel: 'Intermedio',
    materiales: [
      'Cuaderno de dibujo A4',
      'Lápices, rotuladores y materiales de entintado',
      'Plantillas para viñetas (incluidas)',
      'Referencias bibliográficas',
    ],
    profesor: 'Mtro. Diego Fuentes',
    cupoMaximo: 12,
  },
  {
    id: 14,
    categoria: 'Dibujo',
    titulo: 'Diseño de Personajes',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1599498448014-67308b2271b9',
      'https://images.unsplash.com/photo-1615412704911-55d589229865',
    ],
    descripcionCorta: ['🎭 Anatomía creativa', '🎨 Desarrollo de estilo'],
    descripcionCompleta:
      'Taller especializado en la creación y desarrollo de personajes para diversas aplicaciones: ilustración, animación, cómic y videojuegos. Aprenderás a diseñar personajes consistentes, expresivos y con personalidad definida, desde la conceptualización hasta su finalización. Se abordarán tanto aspectos técnicos como narrativos del diseño de personajes.',
    temario: [
      'Anatomía básica y su estilización',
      'Desarrollo de arquetipos y personalidades',
      'Diseño de poses dinámicas y expresivas',
      'Creación de hojas modelo (model sheets)',
      'Vestuario, accesorios y elementos distintivos',
      'Expresión facial y corporal',
      'Adaptación de personajes a diferentes estilos',
    ],
    fechaInscripcion: '28 de abril',
    costoInscripcion: '$600 MXN',
    colegiatura: '$1400 MXN/mes',
    duracion: '4 meses',
    horarios: ['Martes y jueves 18:00-20:00', 'Sábados 15:00-19:00'],
    nivel: 'Intermedio a avanzado',
    materiales: [
      'Cuaderno de bocetos profesional',
      'Set completo de lápices y materiales de coloreado',
      'Referencias anatómicas (incluidas)',
      'Tableta digitalizadora (recomendada pero opcional)',
    ],
    profesor: 'Mtra. Sofía Reyes',
    cupoMaximo: 10,
  },
  {
    id: 15,
    categoria: 'Dibujo',
    titulo: 'Modelado en Plastilina',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1607611439230-fcbf50e42f5c',
      'https://images.unsplash.com/photo-1581801906542-8f7a7d8eae0a',
    ],
    descripcionCorta: ['🎭 Creación de figuras', '🖌️ Escultura y detalle'],
    descripcionCompleta:
      'Curso práctico de modelado tridimensional utilizando plastilina profesional. Aprenderás técnicas para crear figuras, personajes y esculturas con un material versátil y accesible. Ideal tanto para principiantes como para artistas que desean mejorar su comprensión del volumen y la forma, o como complemento para diseñadores de personajes e ilustradores.',
    temario: [
      'Materiales y herramientas para modelado',
      'Técnicas básicas: bolas, rollos, planchas',
      'Construcción de estructuras de soporte',
      'Modelado de formas orgánicas e inorgánicas',
      'Creación de personajes y figuras expresivas',
      'Texturas y acabados superficiales',
      'Conservación de piezas y moldes básicos',
    ],
    fechaInscripcion: '30 de abril',
    costoInscripcion: '$650 MXN',
    colegiatura: '$1500 MXN/mes',
    duracion: '3 meses',
    horarios: ['Lunes y miércoles 18:00-20:00', 'Domingos 10:00-14:00'],
    nivel: 'Todos los niveles',
    materiales: [
      'Kit de plastilina profesional (incluido)',
      'Herramientas básicas de modelado',
      'Bases y estructura de alambre',
      'Material para acabados',
    ],
    profesor: 'Mtro. Ricardo Ávila',
    cupoMaximo: 10,
  },

  // 💻 Categoría: Digital (Azul)
  {
    id: 16,
    categoria: 'Digital',
    titulo: 'Taller de Digital',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1545665277-5937489579f2',
      'https://images.unsplash.com/photo-1626785774573-4b799315345d',
    ],
    descripcionCorta: ['🖥️ Ilustración digital', '🎨 Herramientas avanzadas'],
    descripcionCompleta:
      'Curso completo de ilustración digital que abarca desde los fundamentos hasta técnicas avanzadas. Aprenderás a utilizar software profesional para crear ilustraciones de calidad, dominando herramientas, flujos de trabajo y métodos específicos del medio digital. Ideal para artistas tradicionales que desean explorar el mundo digital o principiantes interesados en esta disciplina.',
    temario: [
      'Introducción al software de ilustración digital',
      'Herramientas y funciones fundamentales',
      'Del boceto tradicional al acabado digital',
      'Uso de capas y modos de fusión',
      'Color digital: teoría y aplicación',
      'Pinceles y texturas personalizadas',
      'Workflow profesional y preparación de archivos',
    ],
    fechaInscripcion: '10 de abril',
    costoInscripcion: '$650 MXN',
    colegiatura: '$1500 MXN/mes',
    duracion: '4 meses',
    horarios: ['Lunes y miércoles 17:00-19:00', 'Sábados 10:00-14:00'],
    nivel: 'Principiante a intermedio',
    materiales: [
      'Tableta gráfica (propia o préstamo con depósito)',
      'Software específico (licencia educativa incluida)',
      'Memoria USB para respaldo',
      'Acceso a computadoras del taller',
    ],
    profesor: 'Mtra. Verónica Campos',
    cupoMaximo: 10,
  },
  {
    id: 17,
    categoria: 'Digital',
    titulo: 'Taller de Animación 2D',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1611162616475-46b635cb6868',
      'https://images.unsplash.com/photo-1527066236128-2ff79f7b9705',
    ],
    descripcionCorta: ['🎬 Principios de animación', '✏️ Movimiento fluido'],
    descripcionCompleta:
      'Curso especializado en animación bidimensional digital. Aprenderás los principios fundamentales de la animación y su aplicación a través de software especializado. Desde secuencias de movimiento básicas hasta proyectos más complejos, desarrollarás las habilidades necesarias para dar vida a personajes y elementos gráficos con fluidez y expresividad.',
    temario: [
      'Principios básicos de la animación',
      'Software de animación 2D: herramientas y flujo de trabajo',
      'Animación frame by frame y por interpolación',
      'Timing y spacing: el ritmo del movimiento',
      'Creación de ciclos y secuencias',
      'Animación de personajes: expresión y personalidad',
      'Proyecto final: cortometraje animado simple',
    ],
    fechaInscripcion: '15 de abril',
    costoInscripcion: '$700 MXN',
    colegiatura: '$1600 MXN/mes',
    duracion: '5 meses',
    horarios: ['Martes y jueves 17:00-19:00', 'Sábados 15:00-19:00'],
    nivel: 'Intermedio',
    materiales: [
      'Tableta gráfica (requerida)',
      'Software de animación (licencia educativa incluida)',
      'Disco duro externo para proyectos',
      'Acceso al laboratorio digital',
    ],
    profesor: 'Mtro. Héctor Jiménez',
    cupoMaximo: 8,
  },
  {
    id: 18,
    categoria: 'Digital',
    titulo: 'Taller de Ing. en Papel',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1615184240098-acf68a3e1024',
      'https://images.unsplash.com/photo-1627163439134-7a8c47e08208',
    ],
    descripcionCorta: ['📜 Origami avanzado', '✂️ Construcción de figuras'],
    descripcionCompleta:
      'Taller práctico enfocado en la ingeniería y arquitectura de papel, combinando técnicas de origami avanzado, pop-up y modelado tridimensional en papel. Aprenderás a diseñar y construir estructuras complejas utilizando únicamente papel y adhesivos, desarrollando proyectos que van desde tarjetas pop-up hasta esculturas de papel de gran formato.',
    temario: [
      'Fundamentos de la ingeniería en papel',
      'Técnicas básicas: pliegues, cortes, ensamblajes',
      'Mecanismos pop-up: ángulos, capas, movimiento',
      'Diseño de estructuras autoportantes',
      'Papel 3D: del plano al volumen',
      'Acabados y presentación profesional',
      'Proyecto final: libro pop-up o escultura',
    ],
    fechaInscripcion: '20 de abril',
    costoInscripcion: '$550 MXN',
    colegiatura: '$1300 MXN/mes',
    duracion: '3 meses',
    horarios: ['Miércoles y viernes 16:00-18:00', 'Sábados 10:00-14:00'],
    nivel: 'Todos los niveles',
    materiales: [
      'Kit básico de papeles especiales (incluido)',
      'Herramientas de precisión: cutter, reglas metálicas',
      'Adhesivos específicos para papel',
      'Carpeta para transporte de proyectos',
    ],
    profesor: 'Mtra. Ana Luisa Torres',
    cupoMaximo: 12,
  },
  {
    id: 19,
    categoria: 'Digital',
    titulo: 'Taller de Modelado 3D',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1617791160505-6f00504e3519',
      'https://images.unsplash.com/photo-1628359355624-855775b5c9c4',
    ],
    descripcionCorta: ['🖥️ Modelado digital', '🎭 Creación de personajes'],
    descripcionCompleta:
      'Curso especializado en modelado tridimensional digital con software profesional. Aprenderás a crear modelos 3D de personajes, objetos y escenarios, desde el concepto hasta el renderizado final. Un taller práctico que te proporcionará las habilidades fundamentales para desenvolverte en el campo del 3D, ya sea para videojuegos, animación o impresión 3D.',
    temario: [
      'Introducción al software de modelado 3D',
      'Modelado poligonal: técnicas y metodología',
      'Escultura digital para personajes y orgánicos',
      'Texturizado y materiales básicos',
      'Iluminación y renderizado básico',
      'Composición y presentación de proyectos 3D',
      'Introducción a la impresión 3D',
    ],
    fechaInscripcion: '25 de abril',
    costoInscripcion: '$750 MXN',
    colegiatura: '$1800 MXN/mes',
    duracion: '5 meses',
    horarios: ['Martes y jueves 18:00-20:00', 'Sábados 15:00-19:00'],
    nivel: 'Principiante a intermedio',
    materiales: [
      'Acceso a estaciones de trabajo de alto rendimiento',
      'Software profesional (licencia educativa incluida)',
      'Disco duro externo para proyectos (requerido)',
      'Tableta gráfica para escultura digital (disponible en sala)',
    ],
    profesor: 'Mtro. Luis Martínez',
    cupoMaximo: 8,
  },
  {
    id: 20,
    categoria: 'Digital',
    titulo: 'Aerografía',
    imagen:
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
    imagenes: [
      'https://epd.edu.mx/prueba/wp-content/uploads/2020/08/20190528_171750-1011x1024.jpg',
      'https://images.unsplash.com/photo-1595079566962-23a88bc8ab5e',
      'https://images.unsplash.com/photo-1569172367135-3bacaae17cb6',
    ],
    descripcionCorta: ['🎨 Técnicas de aerógrafo', '🖌️ Aplicación en diseño'],
    descripcionCompleta:
      'Taller especializado en la técnica del aerógrafo, una herramienta versátil que permite crear acabados profesionales con gran precisión y suavidad. Aprenderás a utilizar y mantener el equipo, así como diversas técnicas para la aplicación en diferentes superficies y proyectos, desde ilustración hasta personalización de objetos.',
    temario: [
      'Introducción al aerógrafo: tipos y funcionamiento',
      'Mantenimiento y resolución de problemas comunes',
      'Técnicas básicas: degradados, texturas, enmascarado',
      'Control de presión y distancia',
      'Aplicación en diferentes superficies',
      'Efectos especiales: metalizados, transparencias, volumen',
      'Proyectos prácticos: ilustración, personalización',
    ],
    fechaInscripcion: '28 de abril',
    costoInscripcion: '$600 MXN',
    colegiatura: '$1400 MXN/mes',
    duracion: '3 meses',
    horarios: ['Lunes y miércoles 18:00-20:00', 'Domingos 10:00-14:00'],
    nivel: 'Principiante a intermedio',
    materiales: [
      'Kit de aerógrafo básico (en préstamo durante el curso)',
      'Compresor de uso compartido',
      'Pinturas específicas para aerografía',
      'Materiales de enmascarado y superficies de práctica',
    ],
    profesor: 'Mtro. Javier Robles',
    cupoMaximo: 10,
  },
];
